return function(self)
    self.inst:ListenForEvent("goingtodie", function(inst)
        inst.components.talker:Say(GetString(inst, "ANNOUNCE_DYING"))
    end)
    self.inst:ListenForEvent("feelsuffering", function(inst)
        inst.components.talker:Say(GetString(inst, "ANNOUNCE_SUFFERING"))
    end)
    self.inst:ListenForEvent("feelhardpain", function(inst)
        inst.components.talker:Say(GetString(inst, "ANNOUNCE_PAIN"))
    end)
    self.inst:ListenForEvent("feelirritation", function(inst)
        inst.components.talker:Say(GetString(inst, "ANNOUNCE_IRRITATED"))
    end)
end
