return function(self)
    self.inst:ListenForEvent("irradiated_critical", function(inst)
        inst.components.talker:Say(GetString(inst, "ANNOUNCE_CRITICAL_IRRADIATED"))
    end)
    self.inst:ListenForEvent("irradiated_high", function(inst)
        inst.components.talker:Say(GetString(inst, "ANNOUNCE_HIGH_IRRADIATED"))
    end)
    self.inst:ListenForEvent("irradiated_med", function(inst)
        inst.components.talker:Say(GetString(inst, "ANNOUNCE_MED_IRRADIATED"))
    end)
    self.inst:ListenForEvent("irradiated_low", function(inst)
        inst.components.talker:Say(GetString(inst, "ANNOUNCE_LOW_IRRADIATED"))
    end)
end
