return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 11,
  height = 9,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 3,
  nextobjectid = 14,
  properties = {},
  tilesets = {
    {
      name = "Don't Starve Together Terrains",
      firstgid = 1,
      filename = "../../../../../../Don't Starve Mod Tools/mod_tools/Tiled/Don't Starve Together Tileset/Don't Starve Together Terrains.tsx"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 11,
      height = 9,
      id = 1,
      name = "BG_TILES",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 9, 9, 9, 9, 9, 0, 9, 0,
        0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0,
        0, 9, 9, 6, 6, 6, 6, 6, 9, 9, 0,
        0, 9, 9, 6, 6, 6, 6, 6, 9, 9, 0,
        0, 0, 9, 6, 6, 6, 6, 6, 9, 9, 9,
        9, 9, 9, 6, 6, 6, 6, 6, 9, 9, 0,
        0, 9, 9, 6, 6, 6, 6, 6, 9, 9, 0,
        0, 0, 9, 9, 9, 0, 9, 9, 9, 0, 0,
        0, 0, 9, 0, 0, 0, 0, 9, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "FG_OBJECTS",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "Junk Lamp",
          type = "vullard_lamp",
          shape = "rectangle",
          x = 422.542,
          y = 195.413,
          width = 21.7468,
          height = 23.3561,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "Junk Pillar",
          type = "junk_pillar",
          shape = "rectangle",
          x = 368.766,
          y = 153.794,
          width = 36.4154,
          height = 37.9327,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "Junk Lamp 2",
          type = "vullard_lamp",
          shape = "rectangle",
          x = 250.691,
          y = 193.762,
          width = 25.7942,
          height = 25.0356,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "Smelter",
          type = "vullard_smelter",
          shape = "rectangle",
          x = 318.695,
          y = 285.041,
          width = 65.2442,
          height = 68.2788,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "Junk Lamp3",
          type = "vullard_lamp",
          shape = "rectangle",
          x = 424.114,
          y = 357.632,
          width = 24.2769,
          height = 24.2769,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "Junk Lamp 4",
          type = "vullard_lamp",
          shape = "rectangle",
          x = 256.037,
          y = 351.08,
          width = 27.3115,
          height = 28.8288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "Anvil",
          type = "rt_anvil",
          shape = "rectangle",
          x = 276.394,
          y = 272.009,
          width = 22.0009,
          height = 28.8288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "vullard_home",
          type = "",
          shape = "rectangle",
          x = 297,
          y = 195,
          width = 81,
          height = 76,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = -45,
          y = -42,
          width = 0,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
